### ISSUE TITLE
imagem destacada dos posts/noticias

### ISSUE THREAD

**Issue by dricaveloso** [CoordCulturaDigital-Minc/Argent-Neue#9]
ajustar CSS

**Comment by tmergulhao** [comment]
A imagem tem que ter um tamanho mínimo para ser destaque.

**Comment by dricaveloso** [comment]
thiago, me refiro a esta página;

http://sniic.cultura.gov.br/noticias/

a imagem destacada ainda aparece sem alinhamento...

**Comment by dricaveloso** [comment]
a página ficou massa, pra fechar faltou alinhar a imagem destacada na página do post!
